# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpDialogGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpDialogGUI(object):
    def setupUi(self, HelpDialogGUI):
        HelpDialogGUI.setObjectName("HelpDialogGUI")
        HelpDialogGUI.resize(520, 265)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HelpDialogGUI.sizePolicy().hasHeightForWidth())
        HelpDialogGUI.setSizePolicy(sizePolicy)
        HelpDialogGUI.setMaximumSize(QtCore.QSize(520, 265))
        self.label = QtWidgets.QLabel(HelpDialogGUI)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 271))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(HelpDialogGUI)
        self.pushButton.setGeometry(QtCore.QRect(440, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(HelpDialogGUI)
        QtCore.QMetaObject.connectSlotsByName(HelpDialogGUI)

    def retranslateUi(self, HelpDialogGUI):
        _translate = QtCore.QCoreApplication.translate
        HelpDialogGUI.setWindowTitle(_translate("HelpDialogGUI", "Pomoc"))
        self.label.setText(_translate("HelpDialogGUI", "<html><head/><body><p><img src=\"LIB/icons/help.jpg\"/></p></body></html>"))
        self.pushButton.setText(_translate("HelpDialogGUI", "OK"))
from LIB import resources_rc