# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saveOptionsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saveOptionsGUI(object):
    def setupUi(self, saveOptionsGUI):
        saveOptionsGUI.setObjectName("saveOptionsGUI")
        saveOptionsGUI.resize(519, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(saveOptionsGUI.sizePolicy().hasHeightForWidth())
        saveOptionsGUI.setSizePolicy(sizePolicy)
        self.groupBox = QtWidgets.QGroupBox(saveOptionsGUI)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 501, 131))
        self.groupBox.setObjectName("groupBox")
        self.autoSaveCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.autoSaveCheckBox.setEnabled(True)
        self.autoSaveCheckBox.setGeometry(QtCore.QRect(10, 20, 181, 20))
        self.autoSaveCheckBox.setChecked(True)
        self.autoSaveCheckBox.setObjectName("autoSaveCheckBox")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(10, 97, 161, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.timeIntervalSpinBox = QtWidgets.QSpinBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeIntervalSpinBox.sizePolicy().hasHeightForWidth())
        self.timeIntervalSpinBox.setSizePolicy(sizePolicy)
        self.timeIntervalSpinBox.setMinimum(1)
        self.timeIntervalSpinBox.setMaximum(120)
        self.timeIntervalSpinBox.setProperty("value", 10)
        self.timeIntervalSpinBox.setObjectName("timeIntervalSpinBox")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.filePathLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.filePathLineEdit.setGeometry(QtCore.QRect(10, 70, 451, 20))
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 45, 151, 16))
        self.label_3.setObjectName("label_3")
        self.selectPathBtn = QtWidgets.QToolButton(self.groupBox)
        self.selectPathBtn.setGeometry(QtCore.QRect(465, 70, 31, 19))
        self.selectPathBtn.setObjectName("selectPathBtn")
        self.OKButton = QtWidgets.QPushButton(saveOptionsGUI)
        self.OKButton.setGeometry(QtCore.QRect(355, 150, 75, 23))
        self.OKButton.setObjectName("OKButton")
        self.closeButton = QtWidgets.QPushButton(saveOptionsGUI)
        self.closeButton.setGeometry(QtCore.QRect(435, 150, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMaximumSize(QtCore.QSize(75, 23))
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(saveOptionsGUI)
        QtCore.QMetaObject.connectSlotsByName(saveOptionsGUI)

    def retranslateUi(self, saveOptionsGUI):
        _translate = QtCore.QCoreApplication.translate
        saveOptionsGUI.setWindowTitle(_translate("saveOptionsGUI", "Opcje zapisu pomiarów"))
        self.groupBox.setTitle(_translate("saveOptionsGUI", "Zapis automatyczny"))
        self.autoSaveCheckBox.setText(_translate("saveOptionsGUI", "Zapisuj pomiary automatycznie"))
        self.label_2.setText(_translate("saveOptionsGUI", "Interwał zapisu: "))
        self.label.setText(_translate("saveOptionsGUI", "min"))
        self.label_3.setText(_translate("saveOptionsGUI", "Wybierz miejsce zapisu:"))
        self.selectPathBtn.setText(_translate("saveOptionsGUI", "..."))
        self.OKButton.setText(_translate("saveOptionsGUI", "OK"))
        self.closeButton.setText(_translate("saveOptionsGUI", "Zamknij"))
